site_name: Моя документация
site_description: "Крутой сайт с документацией"
site_author: "Ваше Имя"
site_url: "https://ваш-username.github.io/mkdocs/"

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
  language: ru

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true 
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables

nav:
  - Главная: index.md
  - Начало работы: getting-started.md
  - MkDocs: mkdocs.md
